// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var root;
  root = 'undefined' !== typeof window && null != window ? window : 'undefined' !== typeof global && null != global ? global : this;
  root._module_ = function (ns, f, context) {
    var hist, name;
    if (null == context)
      context = root;
    if (null != context)
      context;
    else
      context = root;
    hist = [];
    for (var cache$ = ns.split('.'), i$ = 0, length$ = cache$.length; i$ < length$; ++i$) {
      name = cache$[i$];
      if (!(null != context[name]))
        context[name] = {};
      context = context[name];
      hist.push(context);
    }
    return f.apply(context, hist);
  };
  root._include_ = function (target, ns) {
    var key, val;
    for (key in ns) {
      val = ns[key];
      target[key] = val;
    }
    return ns;
  };
}.call(this);
